### ISSUE TITLE
Bad DateTime decoding

### ISSUE THREAD

**Issue by rembish** [seznam/fastrpc#21]
`python-fastrpc` fails to decode `DateTime` object with date in year **2100**.
Code to reproduce problem:
```python
from fastrpc import dumps, loads, DateTime
d = DateTime("2100-01-01")
t = dumps((d, ), useBinary=True)
s = loads(t)[0]
assert d.unixTime == s.unixTime
```
This code raises `AssertionError`. Results for inspiration:
```python
d, s == (DateTime("21000101T00:00:00+0000"), DateTime("21000101T00:00:00+0000"))
d.unixTime, s.unixTime == (4102441200, -192526096)  # Error here
```

**Comment by rembish** [comment]
Reproducible on 5.0.9 and 7.0.2.

**Comment by rembish** [comment]
It can be something like "year 2038 problem", but it works for next years:
> 2038 2107 2108 2109 2110 2111 2112 2113 2114 2115 2116 2117 2118 2119 2120 2121 2122 2123 2124 2125 2126 2127 2128 2129 2130 2131 2132 2133 2134 2135 2136 2137 2138 2139 2140 2141 2142 2143 2144 2145 2146 2147 2148 2149 2150 2151 2152 2153 2154 2155 2156 2157 2158 2159 2160 2161 2162 2163 2164 2165 2166 2167 2168 2169 2170 2171 2172 2173 2174 2175 2176 2177 2178 2179 2180 2181 2182 2183 2184 2185 2186 2187 2188 2189 2190 2191 2192 2193 2194 2195 2196 2197 2198 2199 2200 2201 2202 2203 2204 2205 2206 2207 2208 2209 2210 2211 2212 2213 2214 2215 2216 2217 2218 2219 2220 2221 2222 2223 2224 2225 2226 2227 2228 2229 2230 2231 2232 2233 2234 2235 2236 2237 2238 2239 2240 2241 2242 2243 2244 2245 2246 2247 2248 2249 2250 2251 2252 2253 2254 2255 2256 2257 2258 2259 2260 2261 2262 2263 2264 2265 2266 2267 2268 2269 2270 2271 2272 2273 2274 2275 2276 2277 2278 2279 2280 2281 2282 2283 2284 2285 2286 2287 2288 2289 2290 2291 2292 2293 2294 2295 2296 2297 2298 2299 2300 2301 2302 2303 2304 2305 2306 2307 2308 2309 2310 2311 2312 2313 2314 2315 2316 2317 2318 2319 2320 2321 2322 2323 2324 2325 2326 2327 2328 2329 2330 2331 2332 2333 2334 2335 2336 2337 2338 2339 2340 2341 2342 2343 2344 2345 2346 2347 2348 2349 2350 2351 2352 2353 2354 2355 2356 2357 2358 2359 2360 2361 2362 2363 2364 2365 2366 2367 2368 2369 2370 2371 2372 2373 2374 2375 2376 2377 2378 2379 2380 2381 2382 2383 2384 2385 2386 2387 2388 2389 2390 2391 2392 2393 2394 2395 2396 2397 2398 2399 2400 2401 2402 2403 2404 2405 2406 2407 2408 2409 2410 2411 2412 2413 2414 2415 2416 2417 2418 2419 2420 2421 2422 2423 2424 2425 2426 2427 2428 2429 2430 2431 2432 2433 2434 2435 2436 2437 2438 2439 2440 2441 2442 2443 2444 2445 2446 2447 2448 2449 2450 2451 2452 2453 2454 2455 2456 2457 2458 2459 2460 2461 2462 2463 2464 2465 2466 2467 2468 2469 2470 2471 2472 2473 2474 2475 2476 2477 2478 2479 2480 2481 2482 2483 2484 2485 2486 2487 2488 2489 2490 2491 2492 2493 2494 2495 2496 2497 2498 2499 2500 2501 2502 2503 2504 2505 2506 2507 2508 2509 2510 2511 2512 2513 2514 2515 2516 2517 2518 2519 2520 2521 2522 2523 2524 2525 2526 2527 2528 2529 2530 2531 2532 2533 2534 2535 2536 2537 2538 2539 2540 2541 2542 2543 2544 2545 2546 2547 2548 2549 2550 2551 2552 2553 2554 2555 2556 2557 2558 2559 2560 2561 2562 2563 2564 2565 2566 2567 2568 2569 2570 2571 2572 2573 2574 2575 2576 2577 2578 2579 2580 2581 2582 2583 2584 2585 2586 2587 2588 2589 2590 2591 2592 2593 2594 2595 2596 2597 2598 2599 2600 2601 2602 2603 2604 2605 2606 2607 2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618 2619 2620 2621 2622 2623

**Comment by FUSAKLA** [comment]
I tested it for different years and bug occurs only in year intervals
2039 - 2106 and than 2624 - 3000 (more i didn't test)
all other years seems to be ok

**Comment by volca02** [comment]
Frankly, this is not going to be an easily fixable.

Internally, the datetime type is a combination of decomposed datetime with timezone and 32bit unix timestamp that is attached to it, which is pretty much an independent value (in a few cases, these are kept in sync, but that is probably a minority).

This is a historic design decision which is problematic in pretty much any project FRPC is used in.

Best solution in my view would be to abandon the DateTime type altogether and replace it with a simple 64bit timestamp type, but some projects need timezone to be intact and transferred, which complicates things.

We could in theory rise the protocol version and implement this differently (enlarge the timestamp to keep all bits), but that would break existing projects that would not understand the new protocol.

**Comment by volca02** [comment]
Current plan is to push a protocol change in fastrpc8, which will extend the unixTime field in the binary encoding to contain whole 8 bytes of the timestamp.

If there's the need to transfer just time_t unixtime, an option is to use int instead, which will have the benefit of less bytes transferred (currently the datetime is encoded to 10 bytes on wire, of which 4 are the 32bit unixtime field).

**Comment by volca02** [comment]
This is fixed in the fastrpc8 branch and will be a part of the release of version 8.

For the purpose of easy migration, it will require one change in the code (namely specifying protocolVersionMajor):

```
from fastrpc import dumps, loads, DateTime
d = DateTime("2100-01-01")
t = dumps((d, ), useBinary=True, protocolVersionMajor=3)
s = loads(t)[0]
assert d.unixTime == s.unixTime
```
