### ISSUE TITLE
fastrp.Boolean isn't bool comparable

### ISSUE THREAD

**Issue by rembish** [seznam/fastrpc#26]
There are few issues with `fastrpc.Boolean`
* they aren't like `bool`s:
```python
from fastrpc import Boolean
Boolean(True) is True  # => False
Boolean(False) is False  # => False
Boolean(True).__nonzero__()  # raises AttributeError
```
* 7.x vs 5.x API problem:
```python
from fastrpc import Boolean
Boolean(True) != None  # 5.x => True
Boolean(True) != None  # 7.x raises TypeError: arg #2 is not a Boolean
```

**Comment by rembish** [comment]
BTW `if`s work well:
```python
from fastrpc import Boolean
if Boolean(True):
    print("TRUE")
if not Boolean(False):
    print("FALSE")
```

**Comment by volca02** [comment]
`Boolean(True) is True`

This code, and similar (i.e. operator `is`) returning false is understandable, since the instances will never be equal (fastrpc.Boolean is not of a python boolean type). Comparison to None and/or other types will be fixed.
