### ISSUE TITLE
Wrong Datetime serialisation

### ISSUE THREAD

**Issue by KeNaCo** [seznam/fastrpc#52]
Datetime is not serialized according documentation:
> Unix timestamp is stored in little endian order like integer. Other values are in the network order. 

Network order = big endian, but output is ordered as little endian.  
Tested for protocol v1, but v2,v3 may have same issue.

Please let me know about resulting fix(changed implementation or documentation) so I can implement same behaviour in my library.

**Comment by volca02** [comment]
Hi,

are you referring to the year field? I will update the documentation around datetime to be more clear.

I also noticed there is no info about byte order of the string/binary type length specifiers and will update the docs to fix that.

**Comment by volca02** [comment]
I updated the documentation in the wiki.

**Comment by KeNaCo** [comment]
Thank you 👍
