### ISSUE TITLE
Null serialisation vs specification

### ISSUE THREAD

**Issue by KeNaCo** [seznam/fastrpc#54]
Specification says that 2.0 add Null type.
```python
>>> fastrpc.dumps((None,), useBinary=True, protocolVersionMajor=2, protocolVersionMinor=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Null is not supported by protocol version lower than 2.1
```
There is **no** mention of 2.1 protocol version!

**Comment by volca02** [comment]
Looking into the repository, the Null type was added in e5ad7f61f85a6e6ecbc99f5bd6548a59c35f9424 and in the same commit the protocolVersionMinor was rised to 1, so this is clearly a mistake in protocol documentation. I'll fix it here in the wiki.
